### ISSUE TITLE
ImportError: No module named 'event' - Python 3.5.2

### ISSUE THREAD

**Issue by franciscod** [markkorput/pyevento#1]
```
alarm@alarmpi ~]$ python
Python 3.5.2 (default, Jul  3 2016, 09:10:23)
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import evento
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/evento/__init__.py", line 2, in <module>
    from .decorators import triggers_before_event, triggers_after_event, triggers_beforeafter_events
  File "/usr/lib/python3.5/site-packages/evento/decorators.py", line 1, in <module>
    from event import Event
ImportError: No module named 'event'
>>>
```

:disappointed:

**Comment by franciscod** [comment]
Changing the first line of `decorators.py` from this:

``` python
from event import Event
```

to this:

``` python
from .event import Event
```

appears to work!

**Comment by markkorput** [comment]
Thanks @franciscod for the feedback! Python 3.5 wasn't really supported but I applied your fix to the master branch and fixed the tests so it seems to work with python3.5 now.

**Comment by franciscod** [comment]
Woohoo!

**Comment by RutujaWanjari** [comment]
Hello there,

I am getting "ModuleNotFound: No module named event" on -
`from event import Event` 

Also getting "ModuleNotFoundError: No module named '__main__.event'; '__main__' is not a package" on -
`from .event import Event` 

Python Environment -- Python 3.6.4 :: Anaconda custom (64-bit)

**Comment by markkorput** [comment]
Hey @RutujaWanjari, thanks for the feedback.

I'm not familiar with the anaconda distribution so maybe you could clarify when/how you get this error? I did a quick try with the anaconda python and it seemed ok for me. Here's a log from my console (starting in the repo's root directory);

```
(venv) mark:pyevento mark$ python --version
Python 3.6.5 :: Anaconda custom (64-bit)
(venv) mark:pyevento mark$ python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import evento
>>> evt = evento.Event()
>>> evt
<evento.event.Event object at 0x10c0737f0>
>>> def listener():
...   print("ok")
...
>>> evt += listener
>>> evt()
ok
>>>
```
